// <auto-generated />
using System;
using API_MySIRH.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_MySIRH.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220401103952_Createmig")]
    partial class Createmig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_MySIRH.Entities.Collaborateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Civilite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDebutStage")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEntreeSqli")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePremiereExperience")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSortieSqli")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diplomes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeRecrutement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Collaborateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2011, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1987, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2011, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "30783",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(4499),
                            Nom = "BAAZZI",
                            Prenom = "Abdellah"
                        },
                        new
                        {
                            Id = 2,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2009, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2009, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1986, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2009:Ingénieur d'état en génie informatique",
                            Matricule = "30517",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(4781),
                            Nom = "Afaf",
                            Prenom = "El"
                        },
                        new
                        {
                            Id = 3,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2007, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1987, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2010:Ingénieur d'Etat",
                            Matricule = "30595",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(4837),
                            Nom = "Naimi",
                            Prenom = "Youssef"
                        },
                        new
                        {
                            Id = 4,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2012, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1988, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2012:Matser spécialisé en  Informatique|2010:Mastère en informatique|2010:Licence en physique informatique",
                            Matricule = "30903",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(4861),
                            Nom = "LASMAK",
                            Prenom = "Marouane"
                        },
                        new
                        {
                            Id = 5,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2008, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2016:Diplôme d’ingénierie |2006:Diplôme universitaire de technologie",
                            Matricule = "30376",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(4883),
                            Nom = "MAJID",
                            Prenom = "Mostafa"
                        },
                        new
                        {
                            Id = 6,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2007, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1981, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2004:MIAGE|2006:Master MBDS",
                            Matricule = "30238",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(4907),
                            Nom = "BENNAI",
                            Prenom = "Naoufal"
                        },
                        new
                        {
                            Id = 7,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2013, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1990, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2014:MIAGE",
                            Matricule = "30984",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(4925),
                            Nom = "AZZI",
                            Prenom = "Younesse"
                        },
                        new
                        {
                            Id = 8,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2010, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2010, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1987, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2010:Ingenieur",
                            Matricule = "30622",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(4945),
                            Nom = "Siham",
                            Prenom = "Chouki"
                        },
                        new
                        {
                            Id = 9,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2013, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1989, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2013:Master Ingénierie Informatique",
                            Matricule = "30963",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(4970),
                            Nom = "Mahmoud",
                            Prenom = "Boufaddi"
                        },
                        new
                        {
                            Id = 10,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2013, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1981, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2007, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2012:Master spécialisé |2005:Maîtrise Sciences et Techniques (MST)",
                            Matricule = "31012",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(4992),
                            Nom = "KAROUITE",
                            Prenom = "Ouadii"
                        },
                        new
                        {
                            Id = 11,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2016, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1992, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2015:technicien spécialisé en développement m",
                            Matricule = "31281",
                            ModeRecrutement = "Spontané",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5015),
                            Nom = "DIDI",
                            Prenom = "OMAR"
                        },
                        new
                        {
                            Id = 12,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2016, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1992, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2015, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2015:Diplôme d’ingénieur option MIAGE",
                            Matricule = "31317",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5036),
                            Nom = "ALAOUI",
                            Prenom = "ISMAILI"
                        },
                        new
                        {
                            Id = 13,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2016, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1991, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2016, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2016:Ingénieur informatique|2012:Diplôme Universitaire de Technologie",
                            Matricule = "31334",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5060),
                            Nom = "EL",
                            Prenom = "HAMDAOUI"
                        },
                        new
                        {
                            Id = 14,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2016, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1987, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2012:Ingénieur d'état|2009:Licence en génie informatique",
                            Matricule = "31361",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5082),
                            Nom = "ASSAYAH",
                            Prenom = "Mimoun"
                        },
                        new
                        {
                            Id = 15,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1989, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31377",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5099),
                            Nom = "BOUHAFER",
                            Prenom = "Anass"
                        },
                        new
                        {
                            Id = 16,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2017, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1990, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31375",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5143),
                            Nom = "EL",
                            Prenom = "BOUHAFSI"
                        },
                        new
                        {
                            Id = 17,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2017, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1989, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2014, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31447",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5162),
                            Nom = "MAAIDEN",
                            Prenom = "Yassine"
                        },
                        new
                        {
                            Id = 18,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2017, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1987, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31436",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5184),
                            Nom = "BOUKHRIS",
                            Prenom = "Zakaria"
                        },
                        new
                        {
                            Id = 19,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2017, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1989, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2013, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31478",
                            ModeRecrutement = "Recommandation",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5205),
                            Nom = "OUAZZI",
                            Prenom = "Ilyas"
                        },
                        new
                        {
                            Id = 20,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2017, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31479",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5226),
                            Nom = "BRAHIMI",
                            Prenom = "Mouad"
                        },
                        new
                        {
                            Id = 21,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2017, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1993, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31553",
                            ModeRecrutement = "E-Chalenge",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5246),
                            Nom = "EL",
                            Prenom = "AKKEL"
                        },
                        new
                        {
                            Id = 22,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2017, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1989, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2015:Ingénierie des systèmes d’informatique|2017:Ingénierie des systèmes d’informations",
                            Matricule = "31452",
                            ModeRecrutement = "E-Chalenge",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5267),
                            Nom = "OUBAID",
                            Prenom = "Abd"
                        },
                        new
                        {
                            Id = 23,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2017, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2017, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1994, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31394",
                            ModeRecrutement = "E-Chalenge",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5287),
                            Nom = "Echenafi",
                            Prenom = "Imane"
                        },
                        new
                        {
                            Id = 24,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2018, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1993, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31916",
                            ModeRecrutement = "Stage PFE",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5311),
                            Nom = "Aadil",
                            Prenom = "LAHLOU"
                        },
                        new
                        {
                            Id = 25,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2018, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1993, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31683",
                            ModeRecrutement = "E-Chalenge",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5333),
                            Nom = "TOUIYEK",
                            Prenom = "Mehdi"
                        },
                        new
                        {
                            Id = 26,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2018, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1994, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31687",
                            ModeRecrutement = "E-Chalenge",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5352),
                            Nom = "EL",
                            Prenom = "HACHIMI"
                        },
                        new
                        {
                            Id = 27,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1981, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortieSqli = new DateTime(2020, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "0",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5371),
                            Nom = "Kouakou",
                            Prenom = "Miguel"
                        },
                        new
                        {
                            Id = 28,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1994, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31824",
                            ModeRecrutement = "E-Chalenge",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5398),
                            Nom = "TOUMI",
                            Prenom = "Achraf"
                        },
                        new
                        {
                            Id = 29,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1996, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31835",
                            ModeRecrutement = "E-Chalenge",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5422),
                            Nom = "AIT",
                            Prenom = "EL"
                        },
                        new
                        {
                            Id = 30,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1996, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31838",
                            ModeRecrutement = "E-Chalenge",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5465),
                            Nom = "ALBOUFARISSI",
                            Prenom = "Nidal"
                        },
                        new
                        {
                            Id = 31,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1994, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31840",
                            ModeRecrutement = "E-Chalenge",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5487),
                            Nom = "NAJI",
                            Prenom = "Naji"
                        },
                        new
                        {
                            Id = 32,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1992, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31933",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5507),
                            Nom = "Lahmidi",
                            Prenom = "Fouad"
                        },
                        new
                        {
                            Id = 33,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1986, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2009, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31939",
                            ModeRecrutement = "Cooptation",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5525),
                            Nom = "TAYEBI",
                            Prenom = "Aziz"
                        },
                        new
                        {
                            Id = 34,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "31954",
                            ModeRecrutement = "Stage PFE",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5550),
                            Nom = "SOSSEY",
                            Prenom = "ALAOUI"
                        },
                        new
                        {
                            Id = 35,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1990, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2013:M2: Nouvelles technologies|2013:Ingénieur en informatique et réseau",
                            Matricule = "31293",
                            ModeRecrutement = "Cooptation",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5576),
                            Nom = "EL",
                            Prenom = "HILALI"
                        },
                        new
                        {
                            Id = 36,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1995, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2016:Technicien Spécialisé en Développement|2017:Licence Universitaire Professionnelle|2014:Baccalauréat Science Physique|2020:Master Universitaire Professionnelle",
                            Matricule = "31970",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5594),
                            Nom = "CHAFIK",
                            Prenom = "Soufiane"
                        },
                        new
                        {
                            Id = 37,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortieSqli = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32027",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5614),
                            Nom = "Hamdi",
                            Prenom = "Fatima"
                        },
                        new
                        {
                            Id = 38,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1994, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32000",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5636),
                            Nom = "Beraich",
                            Prenom = "Badre"
                        },
                        new
                        {
                            Id = 39,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2020, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1989, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32083",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5661),
                            Nom = "Lagzouli",
                            Prenom = "El"
                        },
                        new
                        {
                            Id = 40,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2020, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1996, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2016:GÉNIE LOGICIEL|2019:LOGICIEL ET SYSTÈME INFORMATIQUE",
                            Matricule = "32080",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5680),
                            Nom = "El",
                            Prenom = "Kaddouri"
                        },
                        new
                        {
                            Id = 41,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32021",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5699),
                            Nom = "Maadane",
                            Prenom = "Fatima"
                        },
                        new
                        {
                            Id = 42,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2020, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32062",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5750),
                            Nom = "Adam",
                            Prenom = "El"
                        },
                        new
                        {
                            Id = 43,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1990, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortieSqli = new DateTime(2020, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "0",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5769),
                            Nom = "Droussi",
                            Prenom = "Nabil"
                        },
                        new
                        {
                            Id = 44,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1987, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortieSqli = new DateTime(2020, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "0",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5790),
                            Nom = "Haouari",
                            Prenom = "Nadir"
                        },
                        new
                        {
                            Id = 45,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2019, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1992, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortieSqli = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "0",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5811),
                            Nom = "Laghoui",
                            Prenom = "Lhoucine"
                        },
                        new
                        {
                            Id = 46,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2020, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1991, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSortieSqli = new DateTime(2020, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "0",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5831),
                            Nom = "Zouitni",
                            Prenom = "Abdelkrim"
                        },
                        new
                        {
                            Id = 47,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2020, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1983, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2009:Ingénierie Concepteur de Systèmes d’info|2004:BTS- Génie Informatique|2001:Baccalauréat",
                            Matricule = "32134",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5853),
                            Nom = "EL",
                            Prenom = "YASNI"
                        },
                        new
                        {
                            Id = 48,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1988, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "0",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5871),
                            Nom = "Bounzaha",
                            Prenom = "Mohamed"
                        },
                        new
                        {
                            Id = 49,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1998, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32227",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5895),
                            Nom = "Chaimaa",
                            Prenom = "Chemmam"
                        },
                        new
                        {
                            Id = 50,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32209",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5913),
                            Nom = "Mounib",
                            Prenom = "El"
                        },
                        new
                        {
                            Id = 51,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1998, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2018:T. S. en développement Informatique",
                            Matricule = "32214",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5930),
                            Nom = "Alaa",
                            Prenom = "Hammeni"
                        },
                        new
                        {
                            Id = 52,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32194",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5953),
                            Nom = "Yassine",
                            Prenom = "Elmousaoui"
                        },
                        new
                        {
                            Id = 53,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32248",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5973),
                            Nom = "Mohamed",
                            Prenom = "Roudani"
                        },
                        new
                        {
                            Id = 54,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1996, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32247",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(5992),
                            Nom = "Mouad",
                            Prenom = "Sifane"
                        },
                        new
                        {
                            Id = 55,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1996, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32245",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6032),
                            Nom = "Mohamed",
                            Prenom = "Zidani"
                        },
                        new
                        {
                            Id = 56,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1996, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32187",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6049),
                            Nom = "Hicham",
                            Prenom = "Farraji"
                        },
                        new
                        {
                            Id = 57,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1998, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32188",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6069),
                            Nom = "Ahlam",
                            Prenom = "Jelti"
                        },
                        new
                        {
                            Id = 58,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1998, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32189",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6089),
                            Nom = "Mohamed",
                            Prenom = "Maghnouj"
                        },
                        new
                        {
                            Id = 59,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateDebutStage = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1999, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32190",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6109),
                            Nom = "Kaoutar",
                            Prenom = "Mehdaoui"
                        },
                        new
                        {
                            Id = 60,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1999, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32239",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6127),
                            Nom = "Abdellah",
                            Prenom = "Dbib"
                        },
                        new
                        {
                            Id = 61,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1986, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "0",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6144),
                            Nom = "Otmani",
                            Prenom = "Amine"
                        },
                        new
                        {
                            Id = 62,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1993, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32287",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6162),
                            Nom = "Lahcen",
                            Prenom = "Ettout"
                        },
                        new
                        {
                            Id = 63,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1993, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32300",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6179),
                            Nom = "Salim",
                            Prenom = "El"
                        },
                        new
                        {
                            Id = 64,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32304",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6195),
                            Nom = "Mourad",
                            Prenom = "El"
                        },
                        new
                        {
                            Id = 65,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1993, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32315",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6213),
                            Nom = "Zakaria",
                            Prenom = "Lahmidi"
                        },
                        new
                        {
                            Id = 66,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1996, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32325",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6231),
                            Nom = "Oussama",
                            Prenom = "Nfaoui"
                        },
                        new
                        {
                            Id = 67,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1988, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32334",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6248),
                            Nom = "Omar",
                            Prenom = "Assanouni"
                        },
                        new
                        {
                            Id = 68,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1995, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32339",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6290),
                            Nom = "Benchamekh",
                            Prenom = "Khalil"
                        },
                        new
                        {
                            Id = 69,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1996, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2021:MASTER - 2ASI",
                            Matricule = "32337",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6307),
                            Nom = "Miloudi",
                            Prenom = "Zakaria"
                        },
                        new
                        {
                            Id = 70,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1993, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32352",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6323),
                            Nom = "Bouharrada",
                            Prenom = "Mohammed"
                        },
                        new
                        {
                            Id = 71,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1990, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "0",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6340),
                            Nom = "Khazrouni",
                            Prenom = "Hassan"
                        },
                        new
                        {
                            Id = 72,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2017:Génie logiciel|2018:Sicences mathématiques et informatique|2021:Ingénierie logiciel",
                            Matricule = "32360",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6358),
                            Nom = "aribech",
                            Prenom = "mohamed"
                        },
                        new
                        {
                            Id = 73,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1991, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2018:Diplôme de Technicien Spécialisé|2011:Baccalauréat",
                            Matricule = "32358",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6375),
                            Nom = "Akhardid",
                            Prenom = "Khadija"
                        },
                        new
                        {
                            Id = 74,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1989, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2016, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2015:Master STRI",
                            Matricule = "32363",
                            ModeRecrutement = "Autre",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6392),
                            Nom = "Azoulay",
                            Prenom = "Zakaria"
                        },
                        new
                        {
                            Id = 75,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32367",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6413),
                            Nom = "Fliti",
                            Prenom = "Mouad"
                        },
                        new
                        {
                            Id = 76,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1994, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32366",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6430),
                            Nom = "Bahi",
                            Prenom = "ben"
                        },
                        new
                        {
                            Id = 77,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32370",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6448),
                            Nom = "Berehil",
                            Prenom = "Walid"
                        },
                        new
                        {
                            Id = 78,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1997, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32377",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6464),
                            Nom = "Naimi",
                            Prenom = "Khalil"
                        },
                        new
                        {
                            Id = 79,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1990, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32380",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6480),
                            Nom = "Lourhaoui",
                            Prenom = "Soukaina"
                        },
                        new
                        {
                            Id = 80,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2021, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1996, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "32392",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6498),
                            Nom = "Benmachi",
                            Prenom = "Hamza"
                        },
                        new
                        {
                            Id = 81,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1992, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2016:Licence en EEA|2019:Ingénieur Automatisme Info Industrielle",
                            Matricule = "32402",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6515),
                            Nom = "Ouahdi",
                            Prenom = "Abdachahid"
                        },
                        new
                        {
                            Id = 82,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1990, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "0",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6556),
                            Nom = "Zakaria",
                            Prenom = "Errafiqi"
                        },
                        new
                        {
                            Id = 83,
                            Civilite = "F",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2022, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1993, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2016, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2016:Ingénieur d’état en génie informatique",
                            Matricule = "32463",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6572),
                            Nom = "Asmae",
                            Prenom = "El"
                        },
                        new
                        {
                            Id = 84,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1994, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePremiereExperience = new DateTime(2017, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "2017:Diplome d'ingénieur informatique",
                            Matricule = "32524",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6593),
                            Nom = "Abderrahmane",
                            Prenom = "Dyar"
                        },
                        new
                        {
                            Id = 85,
                            Civilite = "M",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEntreeSqli = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = new DateTime(1990, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diplomes = "",
                            Matricule = "0",
                            ModeRecrutement = "",
                            ModificationDate = new DateTime(2022, 4, 1, 10, 39, 51, 972, DateTimeKind.Local).AddTicks(6613),
                            Nom = "Fourtit",
                            Prenom = "Abdelaziz"
                        });
                });

            modelBuilder.Entity("API_MySIRH.Entities.Memo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Memos");
                });

            modelBuilder.Entity("API_MySIRH.Entities.Niveau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("API_MySIRH.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("API_MySIRH.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("API_MySIRH.Entities.SkillCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillCenters");
                });

            modelBuilder.Entity("API_MySIRH.Entities.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<bool>("Statut")
                        .HasColumnType("bit");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToDoListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToDoListId");

                    b.ToTable("ToDoItems");
                });

            modelBuilder.Entity("API_MySIRH.Entities.ToDoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("API_MySIRH.Entities.TypeContrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeContrats");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "147a34d7-c4a3-4808-babd-74c2ab4fd44e",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "027ccd5b-a964-4e87-9175-4c50252bfe3a",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MYUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEHBL7iKgZpi8CUL8Wa2uRj/nM2FWRpM+F7AKC1DsRINSOdSNZDkHLSFZb+bWkTVUgA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ec067c7c-1258-4b3e-8f11-ca4b20c91e56",
                            TwoFactorEnabled = false,
                            UserName = "myuser"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API_MySIRH.Entities.ToDoItem", b =>
                {
                    b.HasOne("API_MySIRH.Entities.ToDoList", "ToDoList")
                        .WithMany("ToDoItemList")
                        .HasForeignKey("ToDoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDoList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_MySIRH.Entities.ToDoList", b =>
                {
                    b.Navigation("ToDoItemList");
                });
#pragma warning restore 612, 618
        }
    }
}
